### ISSUE TITLE
Better way of Object creation structure

### ISSUE THREAD

**Issue by k4utech** [hydrogen18/write-parquet-example#1]
Found this from your blog post : http://www.hydrogen18.com/blog/writing-parquet-records.html
I have to agree, by so far your was the simplest one to understand if someone has to simply write in parquet format in their own system without dealing with other infra like spark, hadoop etc. 

I found the object structure creation odd, The class created by avro-maven plugin has a huge code base. Most of the cases business object/pojo structure is already created. 
**_What do you recommend in such case when existing Pojo structure needs to be used as a record  and do not want to generate the same using avro-maven plugin?_**

**Comment by hydrogen18** [comment]
Hi,
This isn't really meant to be a discussion space, but I will give you this answer before closing:

I explored the idea of writing Pojos and it would probably be more work and more code than defining an Avro schema. I couldn't find any documentation about how this library is supposed to work together. I didn't want to invest the time into understanding the internals of it.

I don't think this Parquet library is actually meant to be used by 3rd party developers like myself. I'm guessing most of the use cases for it are by developers of the library itself.

Eric
